#!/bin/bash

set -e

SERVICE="org.kde.KWin"
DBUS_PATH="/org/kde/KWin/InputDevice"
INTERFACE="org.kde.KWin.InputDevice"
METHOD_GET="org.freedesktop.DBus.Properties.Get"
METHOD_SET="org.freedesktop.DBus.Properties.Set"

function find_touchpad {
    DM_INTERFACE="org.kde.KWin.InputDeviceManager"
    DM_PROPERTY="devicesSysNames"

    for sysname in $(qdbus6 "$SERVICE" "$DBUS_PATH" "$METHOD_GET" "$DM_INTERFACE" "$DM_PROPERTY"); do
        is_touchpad=$(qdbus6 "$SERVICE" "${DBUS_PATH}/${sysname}" "$METHOD_GET" "$INTERFACE" touchpad)

        if [ "$is_touchpad" == "true" ]; then
            echo "$sysname"
            return
        fi
    done

    >&2 echo "Touchpad not found"
    exit 1
}

DBUS_PATH="${DBUS_PATH}/$(find_touchpad)"
PROPERTY="enabled"

#declare -i STATE
case "$1" in
    enable)
        STATE="true"
	;;
    disable)
	STATE="false"
	;;
    *)
        # Get the current status of the touchpad
        STATE=$(qdbus6 "$SERVICE" "$DBUS_PATH" "$METHOD_GET" "$INTERFACE" "$PROPERTY")

        # Flip the status
        STATE=$([[ "$STATE" == "false" ]] && echo true || echo false)
	;;
esac

qdbus6 "$SERVICE" "$DBUS_PATH" "$METHOD_SET" "$INTERFACE" "$PROPERTY" "$STATE"

if [[ "$STATE" == "false" ]]
then
    echo "Touchpad disabled."
else
    echo "Touchpad enabled."
fi
